ALTER TABLE public."productCategories" DISABLE TRIGGER ALL;
SET check_function_bodies = false;
INSERT INTO public."productCategories" (id, name, value) VALUES (10, 'Tables', 'Coffee Tables');
INSERT INTO public."productCategories" (id, name, value) VALUES (11, 'Tables', 'Consoles');
INSERT INTO public."productCategories" (id, name, value) VALUES (12, 'Tables', 'Dining Tables');
INSERT INTO public."productCategories" (id, name, value) VALUES (17, 'Digital', 'Collectibles');
INSERT INTO public."productCategories" (id, name, value) VALUES (18, 'Digital', 'Spaces');
INSERT INTO public."productCategories" (id, name, value) VALUES (13, 'Tables', 'Desks');
INSERT INTO public."productCategories" (id, name, value) VALUES (14, 'Storage', 'Storage');
INSERT INTO public."productCategories" (id, name, value) VALUES (22, 'Storage', 'Shelves');
INSERT INTO public."productCategories" (id, name, value) VALUES (23, 'Storage', 'Sideboard');
INSERT INTO public."productCategories" (id, name, value) VALUES (15, 'Decoration', 'Rugs');
INSERT INTO public."productCategories" (id, name, value) VALUES (16, 'Decoration', 'Sculptures');
INSERT INTO public."productCategories" (id, name, value) VALUES (24, 'Decoration', 'Mirrors');
INSERT INTO public."productCategories" (id, name, value) VALUES (6, 'Seating', 'Lounge Chairs');
INSERT INTO public."productCategories" (id, name, value) VALUES (7, 'Seating', 'Ottoman & Poufs');
INSERT INTO public."productCategories" (id, name, value) VALUES (8, 'Seating', 'Sofas');
INSERT INTO public."productCategories" (id, name, value) VALUES (9, 'Seating', 'Stools');
INSERT INTO public."productCategories" (id, name, value) VALUES (5, 'Seating', 'Chairs');
INSERT INTO public."productCategories" (id, name, value) VALUES (19, 'Seating', 'Armchairs');
INSERT INTO public."productCategories" (id, name, value) VALUES (20, 'Seating', 'Bench');
INSERT INTO public."productCategories" (id, name, value) VALUES (25, 'Seating', 'Fireside Chairs');
INSERT INTO public."productCategories" (id, name, value) VALUES (1, 'Lighting', 'Floor Lamps');
INSERT INTO public."productCategories" (id, name, value) VALUES (3, 'Lighting', 'Table Lamps');
INSERT INTO public."productCategories" (id, name, value) VALUES (26, 'Tables', 'Entrance Tables');
INSERT INTO public."productCategories" (id, name, value) VALUES (21, 'Tables', 'Side Tables');
INSERT INTO public."productCategories" (id, name, value) VALUES (4, 'Lighting', 'Ceiling & Pendant Lamps');
INSERT INTO public."productCategories" (id, name, value) VALUES (2, 'Lighting', 'Wall Lamps');
INSERT INTO public."productCategories" (id, name, value) VALUES (27, 'Storage', 'Bookcase');
SELECT pg_catalog.setval('public."productCategories_id_seq"', 27, true);

ALTER TABLE public."productCategories" ENABLE TRIGGER ALL;