ALTER TABLE public.seo DISABLE TRIGGER ALL;
SET check_function_bodies = false;
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/helio_house', 'Helio House', 'Helio House collection by Joe Mortell', NULL, NULL, '4e08b85d-c92c-4b20-b077-12867ace8e92');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/enter_the_workcore', 'Enter The Workcore', 'Enter the Workcore collection by Benoit Challand', NULL, NULL, '69655616-d757-4bfb-9ede-79bd74e38e73');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/quantum', 'Quantum', 'Quantum collection by Leo Caillard', NULL, NULL, 'd2499a23-b70b-4f36-bb3c-bd641fcc7a14');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/table_toys_collection', 'Table Toys Collection', 'Table Toys Collection collection by Zyva Studio', NULL, NULL, 'dcf11408-d4b0-4925-97a5-237009cc4d66');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-infinite_room_01', 'Infinite Room 01', 'Infinite Room 01', '6148306d-98b8-4bae-b3cf-9369a2ef22d7', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-emoji_house_cutlery_-_the_knife', 'Emoji House cutlery - The Knife', 'Emoji House cutlery - The Knife', '9e17429c-a80e-454d-b44f-d85604bd6917', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_chair_#3', 'The Workcore Chair #3', 'The Workcore Chair #3', '89e02207-13a9-43ff-86cd-928c35615bf1', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-to_define', 'Infinite Room Collection', 'Infinite Room Collection', '7eda4f4a-4a1f-4f3b-a860-ebdca78638b1', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-infinite_room_collection_#4', 'Infinite Room Collection 04', 'Infinite Room Collection 04', '970f4a1d-ed9f-4845-920f-d03e36066723', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-la_chaise', 'Courbes Alléchantes Chair', 'Courbes Alléchantes Chair by Axel Chay in Courbes Alléchantes collection', 'd060a40b-5bf9-4dcf-a44c-1d4623f5f24a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/pietro_franceschini-vitamin_chair_-_steel', 'Vitamin Chair Steel', 'The Vitamin Collection has been conceived by Pietro Franceschini as a limited edition for Monde Singulair and comes in a lounge chair and a sofa. The essential lines of the aluminium structure make it an instant icon while the bold velvet volumes of the seat and the back set the minimal vibe of this work.', 'cbcbc1dc-5af3-44da-a81f-d38ca12d2f24', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/médano', 'Médano', 'Medano collection by Estudio Persona', NULL, NULL, '0f26b47b-6616-4769-b44f-a9f580a920d0');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-body_house_cutlery_-_the_fork', 'Body House cutlery - The Fork', 'Body House cutlery - The Fork', '9156736c-823c-4644-b1b1-fc475787ec61', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/joe_mortell-6:00_am', '6:00 AM', '6:00AM by Joe Mortell in Helio House collection', 'dff416a8-f754-4010-b579-0459c0abfaba', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/joe_mortell-4:00_pm', '4:00 PM', '4:00 PM by Joe Mortell in Helio House collection', '5bdc38d2-05b3-49d2-9554-47ff3175527b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/joe_mortell-10:00_pm', '10:00 PM', '10:00 PM by Joe Mortel in Helio House collection', '728cc055-c3fb-46cd-b4f5-2e67349fa18b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_table_#3', 'The Workcore Table #3', 'The Workcore Table #3', '51dcd59a-d0bd-439a-b910-1da5122b1c3b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-infinite_room_03', 'Infinite Room 03', 'dgrhdtjfjyg', '3efae876-07a7-4ebf-bfb6-af9aee96b21a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/léo_caillard-the_grey_venus', 'The Grey Venus', 'The Grey Venus by Leo Caillard in Quantum collection', '51cf0057-a374-40e1-8720-2fe51b76c5fe', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-la_table_basse', 'Courbes Alléchantes Coffee Table', 'Courbes Alléchantes Coffee Table by Axel Chay in Courbes Alléchantes collection', '5b9d6838-8f6a-4a17-a4ee-ca0efebb6d66', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-la_suspension', 'Courbes Alléchantes Ceiling Lamp', 'Courbes Alléchantes Ceiling Lamp by Axel Chay in Courbes Alléchantes collection', '3cb6d282-869f-484d-934f-dc74f4b400a4', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-le_banc', 'Courbes Alléchantes Bench', 'Courbes Alléchantes Bench by Axel Chay in Courbes Alléchantes collection', 'c88da545-06d3-4dcc-842a-ee2158587dd1', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-le_lampadaire', 'Courbes Alléchantes Floor Lamp', 'Courbes Alléchantes Floor Lamp by Axel Chay in Courbes Alléchantes collection', '418cfcf4-4f5f-4518-b4b2-6e8647c31ff3', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-body_house_cutlery_-_the_knife', 'Body House cutlery - The Knife', 'Body House cutlery - The Knife', 'c260f9a2-529e-4e01-be31-e5fcda8a032a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-body_house_cutlery_-_the_spoon', 'Body House cutlery - The Spoon', 'Body House cutlery - The Spoon', '353e942a-9b14-4cbf-8cbc-957df67ed8e0', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-emoji_house_cutlery_-_the_fork', 'Emoji House cutlery - The Fork', 'Emoji House cutlery - The Fork', '489d084b-3221-4568-b12a-7291d88bc96d', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-emoji_house_cutlery_-_the_spoon', 'Emoji House cutlery - The Spoon', 'Emoji House cutlery - The Spoon', '8de8393a-ca7b-46c1-8646-6800efd056af', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-bones_house_cutlery_-_the_fork', 'Bones House cutlery - The Fork', 'Bones House cutlery - The Fork', 'f71c8a7e-1f74-4d19-870d-28464fe61904', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-bones_house_cutlery_-_the_knife', 'Bones House cutlery - The Knife', 'Bones House cutlery - The Knife', '4bf06c11-86f7-4885-b303-c4cc53ba46f6', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/zyva_studio-bones_house_cutlery_-_the_spoon', 'Bones House cutlery - The Spoon', 'Bones House cutlery - The Spoon', '127116d2-6fac-4a31-8139-1dac3b045e9d', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_chair_#2', 'The Workcore Chair #2', 'The Workcore Chair #2', 'c5cdc6cc-76c6-42e2-addb-e2a6c308df99', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_sofa_#1', 'The Workcore Sofa #1', 'The Workcore Sofa #1', '81bbc42d-5223-472e-96b5-bef2a34de7bc', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_easter_egg', 'The Workcore Golden Ticket', 'The Workcore Golden Ticket', '4dfa1fa1-fed9-47ce-bd1f-4564933488d6', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_table_#2', 'The Workcore Table #2', 'The Workcore Table #2', '0ec019f5-74c8-484f-8ec7-c53bb8ec5dce', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_chair_#1', 'The Workcore Chair #1', 'The Workcore Chair #1 by Benoit Challand in Enter the Workcore collection', 'bce80125-ae31-402c-b63a-6f24013a2592', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/courbes_alléchantes', 'Courbes Alléchantes', 'Courbes Alléchantes collection by Axel Chay', NULL, NULL, '73a2c957-1e85-4b96-9669-309cc37f0e00');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_sofa_#2', 'The Workcore Sofa #2', 'The Workcore Sofa #2', '584f4e81-99a8-448b-b55f-9eec53e0e654', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_sofa_#3', 'The Workcore Sofa #3', 'The Workcore Sofa #3', 'bfef769a-ea3f-4104-b8a8-1ede60687fe2', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-the_workcore_table_#1', 'The Workcore Table #1', 'The Workcore Table #1', '3c763eba-b3a1-44b0-ae03-c1926cb1e88f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/vitamin', 'Vitamin', 'The Vitamin Collection has been conceived by Pietro Franceschini as a limited edition for Monde Singulair and comes in a lounge chair and a sofa. The essential lines of the aluminium structure make it an instant icon while the bold velvet volumes of the seat and the back set the minimal vibe of this work.', NULL, NULL, '7a434f3b-e8e1-4003-8642-07f6f222e807');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/pietro_franceschini-vitamin_chair_-_ivory', 'Vitamin Chair Ivory', 'The Vitamin Collection has been conceived by Pietro Franceschini as a limited edition for Monde Singulair and comes in a lounge chair and a sofa. The essential lines of the aluminium structure make it an instant icon while the bold velvet volumes of the seat and the back set the minimal vibe of this work.', 'bbd26621-7560-4a47-933a-7a8a7a0d5863', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benoit_challand-infinite_room_02', 'Infinite Room 02', 'Infinite Room 02', 'e4ccb1fe-25ad-4d21-a1f2-4b623fb94487', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_floor_lamp_-_s', 'Soniah Lightings Floor Lamp - S', 'Cable length – 2,5m
Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable.
UK/US plug upon request.
For indoor use. Outdoor upon request.', '967df91d-8dc5-44ac-97c5-847cceddba84', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/piotr_dabrowa', 'Piotr Dabrowa', 'The Salvante collection is a play between shapes and materials. This special limited edition explores the relationship between Travertine and Onyx, where textures and shapes harmoniously come together to give the designs a sculptural identity while maintaining practical functionality.', NULL, NULL, 'ad8afa77-79e9-4220-9f0e-8b55fcd767dd');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/roche_&_frères-arès_armchair_-_brushed_stainless_steel', 'Arès Armchair - Brushed Steel', 'Special edition in velvet of the iconic Arès armchair, by ROCHE & FRÈRES studio exclusively for Monde Singulier. 
Inspired by the metal parts of armor, the armchair takes on a warrior, masculine side, hence its name “Arès”, evoking the myth of the god of war in Greek mythology. 
Raw in appearance, the curves here bring the balance between strength and softness.', '68fe602a-a3bc-4852-8faa-92cbb419e530', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/pietro_franceschini-vitamin_sofa_-_ivory', 'Vitamin Sofa Ivory', 'The Vitamin Collection has been conceived by Pietro Franceschini as a limited edition for Monde Singulair and comes in a lounge chair and a sofa. 
The essential lines of the aluminium structure make it an instant icon while the bold velvet volumes of the seat and the back set the minimal vibe of this work.', '20b225e6-5383-4dcb-bce5-e4f3ab520932', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/arès', 'Arès', 'Special edition in velvet of the iconic Arès armchair, by ROCHE & FRÈRES studio exclusively for Monde Singulier. Inspired by the metal parts of armor, the armchair takes on a warrior, masculine side, hence its name “Arès”, evoking the myth of the god of war in Greek mythology. Raw in appearance, the curves here bring the balance between strength and softness.', NULL, NULL, '011acd4c-c4a5-429f-809b-43704a7bcc50');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/pietro_franceschini-vitamin_sofa_-_steel', 'Vitamin Sofa Steel', 'The Vitamin Collection has been conceived by Pietro Franceschini as a limited edition for Monde Singulair and comes in a lounge chair and a sofa. 
The essential lines of the aluminium structure make it an instant icon while the bold velvet volumes of the seat and the back set the minimal vibe of this work.', 'a902512b-9054-48fc-a642-fbb5812ad390', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/roche_&_frères-arès_armchair_-_black_mat_steel', 'Arès Armchair - Black Mat Steel', 'Special edition in velvet of the iconic Arès armchair, by ROCHE & FRÈRES studio exclusively for Monde Singulier. 
Inspired by the metal parts of armor, the armchair takes on a warrior, masculine side, hence its name “Arès”, evoking the myth of the god of war in Greek mythology. 
Raw in appearance, the curves here bring the balance between strength and softness.', '639009d5-650e-4cb4-a948-ddaef592e1b5', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/estudio_persona-médano_chair_bouclette', 'Médano Chair Bouclette', 'Discover a haven of solace and inspiration within your personal space as you embrace the Médano Lounge Chair. Its gentle curves and flowing lines, reminiscent of the captivating natural landscape, create an inviting space that encourages relaxation and a sense of calm.', '17580889-a936-4f08-97a0-b1d8bb2be42f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/estudio_persona-médano_chair_velvet', 'Médano Chair Velvet', 'Discover a haven of solace and inspiration within your personal space as you embrace the Médano Lounge Chair. Its gentle curves and flowing lines, reminiscent of the captivating natural landscape, create an inviting space that encourages relaxation and a sense of calm.', '493fd425-a036-4194-ada6-4204dc856a9d', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/estudio_persona-medano_sofa_bouclette', 'Médano Sofa Bouclette', 'The Sofa stands as a testament to the collection''s ethos, with its soft contours and graceful design becoming the centerpiece of comfort and relaxation in your living area. This sofa effortlessly complements any interior, transforming your space into a peaceful sanctuary that radiates timeless beauty.', '1d3e1704-03a9-43e2-b6be-fdc7253d4066', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/estudio_persona-medano_sofa_velvet', 'Médano Sofa Velvet', 'The Sofa stands as a testament to the collection''s ethos, with its soft contours and graceful design becoming the centerpiece of comfort and relaxation in your living area. This sofa effortlessly complements any interior, transforming your space into a peaceful sanctuary that radiates timeless beauty.', 'c75897b5-c75a-4f18-baf9-f1169410b403', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rino_claessens-intersectig_volume_bench_-_gouge', 'Intersecting Volume Bench - Gouged', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. 
This time executed in wood, so the grain of the wood accents the curve of the volumes.', '78f9785b-8fc8-44af-98d2-e5edecaf2a25', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/rino_claessens', 'Intersecting Volume', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. This time executed in wood, so the grain of the wood accents the curve of the volumes.', NULL, NULL, '3a18f32f-c4e8-4e70-91e5-eacf3e0e9f10');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rino_claessens-intersectig_volume_coffee_table', 'Intersecting Volume Coffee Table', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. 
This time executed in wood, so the grain of the wood accents the curve of the volumes.', 'f5b4ffaa-1d9f-48fa-8aa4-2e44e5b11aa9', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rino_claessens-intersectig_volume_bench', 'Intersecting Volume Bench', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. 
This time executed in wood, so the grain of the wood accents the curve of the volumes.', 'f1f37ab9-431b-4877-be1e-4fc7967a0702', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rino_claessens-intersectig_volume_side_table', 'Intersecting Volume Side Table', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. 
This time executed in wood, so the grain of the wood accents the curve of the volumes.', 'd4dbe3c6-9728-4697-b6ad-9aa1a59cbf22', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rino_claessens-intersectig_volume_coffee_table_-_gouge', 'Intersecting Volume Coffee Table - Gouge', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. 
This time executed in wood, so the grain of the wood accents the curve of the volumes.', '00a2af9b-c367-4dfc-9ff5-82ae998c2c93', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rino_claessens-intersecting_volume_side_table_-_gouged', 'Intersecting Volume Side Table - Gouged', 'This collection is formed around the connection that emerges when curved volumes intersect. A recurring theme in Rino’s work, now lead to a side-table, coffee table and bench. 
This time executed in wood, so the grain of the wood accents the curve of the volumes.', 'c32f36c0-1a36-4612-b778-486fae32ef5a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-oval-pendant-lamp', 'Oval Pendant Lamp, Stamp by Christophe Perichon, Monde Singulier', 'Oval Pendant Lamp, Stamp by Christophe Perichon, Monde Singulier', 'bb85929e-824d-4e28-80ee-60eb00f77f03', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-round-pendant-lamp', 'Round Pendant Lamp, Stamp by Christophe Perichon, Monde Singulier', 'Round Pendant Lamp, Stamp by Christophe Perichon, Monde Singulier', 'd2cdaa79-828b-4b86-92f2-c20b222ed8e9', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/adelie_ducasse-modern_stripes_floor_lamp_-_boston', 'Modern Stripes Floor Lamp - Boston', 'Sea Ranch on a foggy November morning, Adélie finds herself in a wooden cabin with large windows and a vast ceiling with its inclination typical of modernist architecture.
She is immersed in nature, facing a raging ocean... grey tones, clear light.
She envisions this collection in black and white, a balance of grey and off-white stripes, supported by a solid, elegant black base.
The collection consists of 4 sculptural lightings and a ceramic mirror.
Meticulously handcrafted in Italy, they embody the rigor and craftsmanship that are characteristic of the Bauhaus influence in her work.', '05f8eea5-1381-40e8-9bad-8bf3625953c7', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/adelie_ducasse-modern_stripes_floor_lamp_-_montauk', 'Modern Stripes Floor Lamp - Montauk', 'Sea Ranch on a foggy November morning, Adélie finds herself in a wooden cabin with large windows and a vast ceiling with its inclination typical of modernist architecture.
She is immersed in nature, facing a raging ocean... grey tones, clear light.
She envisions this collection in black and white, a balance of grey and off-white stripes, supported by a solid, elegant black base.
The collection consists of 4 sculptural lightings and a ceramic mirror.
Meticulously handcrafted in Italy, they embody the rigor and craftsmanship that are characteristic of the Bauhaus influence in her work.', '5a3c1dc7-ee0a-4edc-b030-a12e1bb52fad', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/adelie_ducasse-modern_stripes_mirror_-_malibu', 'Modern Stripes Mirror - Malibu', 'Sea Ranch on a foggy November morning, Adélie finds herself in a wooden cabin with large windows and a vast ceiling with its inclination typical of modernist architecture.
She is immersed in nature, facing a raging ocean... grey tones, clear light.
She envisions this collection in black and white, a balance of grey and off-white stripes, supported by a solid, elegant black base.
The collection consists of 4 sculptural lightings and a ceramic mirror.
Meticulously handcrafted in Italy, they embody the rigor and craftsmanship that are characteristic of the Bauhaus influence in her work.', '06a9acc3-945d-425a-833f-74aecb0fb787', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/adelie_ducasse-modern_stripes_floor_lamp_-_milano', 'Modern Stripes Floor Lamp - Milano', 'Sea Ranch on a foggy November morning, Adélie finds herself in a wooden cabin with large windows and a vast ceiling with its inclination typical of modernist architecture.
She is immersed in nature, facing a raging ocean... grey tones, clear light.
She envisions this collection in black and white, a balance of grey and off-white stripes, supported by a solid, elegant black base.
The collection consists of 4 sculptural lightings and a ceramic mirror.
Meticulously handcrafted in Italy, they embody the rigor and craftsmanship that are characteristic of the Bauhaus influence in her work.', '161ed854-4201-44b7-8ada-70ec1dbb99d8', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/mickael_koska-prickly_pear_wall_lamp_-_s', 'Prickly Pear Wall Lamp - S', 'Anchored and inspired by the Mediterranean region, Mickaël draws from its arid and wild nature that gives birth to his creations.
Intrigued by the prickly pear cactus, which reveals itself to be a natural tool combating soil erosion and contributing to the preservation of the land, Mickaël takes inspiration from it to design this lamp.
Sensuality and softness are the keywords to celebrate this plant. Modeled from the earth protected by the prickly pear, the Pricly Pear wall lamp is born in terracotta through the designer''s hands. 
The opaline shades, resembling fleshy berries, radiate and highlight this natural feat.', 'b99ba673-0021-47e6-920c-06e50cb4124a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/mickael_koska-prickly_pear_wall_lamp_-_m', 'Prickly Pear Wall Lamp - M', 'creations.
Intrigued by the prickly pear cactus, which reveals itself to be a natural tool combating soil erosion and contributing to the preservation of the land, Mickaël takes inspiration from it to design this lamp.
Sensuality and softness are the keywords to celebrate this plant. Modeled from the earth protected by the prickly pear, the Pricly Pear wall lamp is born in terracotta through the designer''s hands. 
The opaline shades, resembling fleshy berries, radiate and highlight this natural feat.', 'd4fd155d-8864-4251-a3ba-2e5347cdaa67', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/adelie_ducasse', 'Modern Stripes', 'Sea Ranch on a foggy November morning, Adélie finds herself in a wooden cabin with large windows and a vast ceiling with its inclination typical of modernist architecture.  She is immersed in nature, facing a raging ocean... grey tones, clear light.  She envisions this collection in black and white, a balance of grey and off-white stripes, supported by a solid, elegant black base.  The collection consists of 4 sculptural lightings and a ceramic mirror.  Meticulously handcrafted in Italy, they embody the rigor and craftsmanship that are characteristic of the Bauhaus influence in her work.', NULL, NULL, '26e0e07b-89e1-4730-9cc6-b3825455d48c');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/adelie_ducasse-modern_stripes_pendant_-_guetary', 'Modern Stripes Ceiling Lamp - Guetary', 'Sea Ranch on a foggy November morning, Adélie finds herself in a wooden cabin with large windows and a vast ceiling with its inclination typical of modernist architecture.
She is immersed in nature, facing a raging ocean... grey tones, clear light.
She envisions this collection in black and white, a balance of grey and off-white stripes, supported by a solid, elegant black base.
The collection consists of 4 sculptural lightings and a ceramic mirror.
Meticulously handcrafted in Italy, they embody the rigor and craftsmanship that are characteristic of the Bauhaus influence in her work.', '326b4391-8f95-465a-a88f-ecddafb443ef', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/benni_allan', 'Benni Allan', 'benni allan image Combining simple construction methods with elevated material treatment, each piece will benefit from a uniqueness based on the finishing. A refined steel top is treated in two different ways to bring out the patina while also creating a distinctive imprint, representing the shape of the column beneath. The bases are made from solid oak planks to represent the trunk, helping to ground each of the pieces. ', NULL, NULL, 'e651c139-a832-48bb-9b70-b03d8956ab4e');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_floor_lamp_-_m', 'Soniah Lightings Floor Lamp - M', 'Cable length – 2,5m
Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable.
UK/US plug upon request.
For indoor use. Outdoor upon request.', 'a79b3efa-9930-4c35-969b-c3c1be985fad', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_floor_lamp_-_l', 'Soniah Lightings Floor Lamp - L', 'Cable length – 2,5m
Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable.
UK/US plug upon request.
For indoor use. Outdoor upon request.', '390e3cf6-90d1-4041-9308-9cdd3a8fb36f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benni_allan-slab_coffee_table_-_l', 'Slab Coffee Table - L', 'Slab is a new collection that offers a series of versatile pieces for any room. Inspired by the relationship of the column and beam in architecture, this collection bring together common building elements in new forms that can transform a space or home.
Combining simple construction methods with elevated material treatment, each piece will benefit from a uniqueness based on the finishing. A refined steel top is treated in two different ways to bring out the patina while also creating a distinctive imprint, representing the shape of the column beneath. The bases are made from solid oak planks to represent the trunk, helping to ground each of the pieces. ', 'c62a91e6-c224-4635-8c46-51c64676804d', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benni_allan-slab_side_table_-_dark', 'Slab Side Table - Dark', 'Slab is a new collection that offers a series of versatile pieces for any room. Inspired by the relationship of the column and beam in architecture, this collection bring together common building elements in new forms that can transform a space or home.
Combining simple construction methods with elevated material treatment, each piece will benefit from a uniqueness based on the finishing. A refined steel top is treated in two different ways to bring out the patina while also creating a distinctive imprint, representing the shape of the column beneath. The bases are made from solid oak planks to represent the trunk, helping to ground each of the pieces. ', 'cc7a891b-7dfe-4414-8048-9248a6bf4766', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/mickael_koska-prickly_pear_wall_lamp_-_l', 'Prickly Pear Wall Lamp - L', 'Anchored and inspired by the Mediterranean region, Mickaël draws from its arid and wild nature that gives birth to his creations.
Intrigued by the prickly pear cactus, which reveals itself to be a natural tool combating soil erosion and contributing to the preservation of the land, Mickaël takes inspiration from it to design this lamp.
Sensuality and softness are the keywords to celebrate this plant. Modeled from the earth protected by the prickly pear, the Pricly Pear wall lamp is born in terracotta through the designer''s hands. 
The opaline shades, resembling fleshy berries, radiate and highlight this natural feat.', '4f2623e8-ed8f-4a9d-a954-23bb79a902b4', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/mickael_koska-prickly_pear_floor_lamp', 'Prickly Pear Floor Lamp', 'Anchored and inspired by the Mediterranean region, Mickaël draws from its arid and wild nature that gives birth to his creations.
Intrigued by the prickly pear cactus, which reveals itself to be a natural tool combating soil erosion and contributing to the preservation of the land, Mickaël takes inspiration from it to design this lamp.
Sensuality and softness are the keywords to celebrate this plant. Modeled from the earth protected by the prickly pear, the Pricly Pear wall lamp is born in terracotta through the designer''s hands. 
The opaline shades, resembling fleshy berries, radiate and highlight this natural feat.', '74cf6975-ef4b-4c0b-8a62-ff203a470d0e', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benni_allan-slab_coffee_table_-_s', 'Slab Coffee Table - S', 'Slab is a new collection that offers a series of versatile pieces for any room. Inspired by the relationship of the column and beam in architecture, this collection bring together common building elements in new forms that can transform a space or home.
Combining simple construction methods with elevated material treatment, each piece will benefit from a uniqueness based on the finishing. A refined steel top is treated in two different ways to bring out the patina while also creating a distinctive imprint, representing the shape of the column beneath. The bases are made from solid oak planks to represent the trunk, helping to ground each of the pieces. ', '4bff6465-dc80-4faa-bf9a-c9d630cd46c9', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/benni_allan-slab_coffee_table_-_m', 'Slab Coffee Table - M', 'Slab is a new collection that offers a series of versatile pieces for any room. Inspired by the relationship of the column and beam in architecture, this collection bring together common building elements in new forms that can transform a space or home.
Combining simple construction methods with elevated material treatment, each piece will benefit from a uniqueness based on the finishing. A refined steel top is treated in two different ways to bring out the patina while also creating a distinctive imprint, representing the shape of the column beneath. The bases are made from solid oak planks to represent the trunk, helping to ground each of the pieces', 'ed7ece51-f5cc-4573-8bc4-87e0f04d0307', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/goons-you_&_me_mirror_-_s', 'You & Me - Just For Me Mirror S', 'Small hanging wall mirror with floating mirror on corrugated zig-zag frame', 'b3c25353-378f-4a5d-a937-00dd4d1b3a0f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/piotr_dabrowa-salvante_s1_side_table', 'Salvante S1 Side Table', 'The Salvante S1 is part of the Salvante collection, a series of designs that explore the relationship between forms and materials.', '164305a9-3513-4afb-a602-0619a27f9014', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/piotr_dabrowa-salvante_bs1_bench', 'Salvante BS1 Bench', 'The Salvante BS1 bench is part of the Salvante collection, a series of designs that explore the relationship between forms and materials.', '117aea2e-46ff-48db-aa3f-37d498ea6f82', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/piotr_dabrowa-salvante_c1_coffee_table', 'Salvante C1 Coffee Table', 'The Salvante C1 is part of the Salvante collection, a series of designs that explore the relationship between forms and materials.', 'cac7bcb8-c50c-4838-9239-0a730c12c82d', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/goons-you_&_me_mirror_-_you_and_me', 'You & Me - One For Me One For You Mirror', 'Large hanging wall mirror with two floating mirrors on corrugated zig-zag frame', '94458093-677b-4677-9709-ef39038d387b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/piotr_dabrowa-salvante_d1_dining_table', 'Salvante D1 Dining Table', 'The Salvante D1 is part of the Salvante collection, a series of designs that explore the relationship between forms and materials.', 'dec974d8-9139-40e0-aef2-089083dd50b1', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/goons-you_and_me_table', 'You & Me - You & Me Table', 'Large entry table for the display of sculptural objects or large floral arrangements. This piece was designed to be positioned in the center of an entry room or a hallway transition.', '2d6602cd-a5da-4d41-9efe-fdbbe4828f92', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/goons-you_&_me_bench_-_me', 'You & Me - Just For Me Bench', 'Single bench with corrugated zig-zag base', '066ce6c6-fcbe-4f89-b536-2837d32fe087', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/goons-you_&_me_mirror_-_l', 'You & Me - Just For Me Mirror L', 'Large hanging wall mirror with floating mirror on corrugated zig-zag frame', 'e8b47727-de6f-4dc4-a5d4-7e6005d36ff4', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/goons-you_&_me_bench_-_you_and_me', 'You & Me - One For Me One For You Bench', 'Double entrance bench with corrugated zig-zag base', '50b3ab54-13bb-4f22-85c6-21bad80489a9', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/goons', 'Goons', 'G o o n s  entrance room collection.', NULL, NULL, '26d2524b-ccfb-4a62-9737-e497859314da');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-courbes_alléchantes_coffee_table', 'Courbes Alléchantes Coffee Table', 'Axel Chay wants to offer a new vision of his work using fabric on everything. It will change the way you understand the object. The thickness of it will modify shapes and sensation.', 'ed628bc1-0db6-4067-bb5f-5f96e37ae430', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/vova_naumov-the_lamb_collection_ottoman', 'The Lamb Ottoman', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', '05c21dbd-6b72-4f96-8cac-8f91c44d28d5', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/vova_naumov-the_lamb_collection_coffee_table_-_klaska', 'Klaksa Coffee Table', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', 'dedea906-bd76-4ce3-82c9-cdd0996ea88b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/disderot-michel_mortier_disderot_table_lamp', 'Michel Mortier Disderot Table Lamp - 10497', 'The Table Lamp 10497 designed in 1972 by Michel Mortier was published at the time by Verre Lumière. Disderot is reissuing this very current model, with its aluminum base and opaline glass lampshade. Exclusively for Monde Singulier, Disderot is releasing a new version of this iconic lighting in three gradient colors: Beige, Green and Blue. The collection also include the Floor Lamp 10527 in the same gradient colors.', 'fb5b8068-483c-499c-b4a6-6105f804d08d', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-courbes_alléchantes_floor_lamp', 'Courbes Alléchantes Floor Lamp', 'Axel Chay wants to offer a new vision of his work using fabric on everything. It will change the way you understand the object. The thickness of it will modify shapes and sensation.', '56b2fe87-d627-4888-a2a5-030fc2d5d508', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/necchi', 'Necchi', 'To complete', NULL, NULL, '2a084466-a93a-41ee-9024-aaa570914a08');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/michel_mortier_disderot', 'Michel Mortier 10497/10527', 'The Floor Lamp 10527 and Table Lamp 10497 designed in 1972 by Michel Mortier were published at the time by Verre Lumière. Disderot is reissuing these two very current models, with their aluminum base and opaline glass lampshade. Exclusively for Monde Singulier, Disderot is releasing a new version of these iconic lighting in three gradient colors: Beige, Green and Blue. ', NULL, NULL, '531a1084-56ee-4cb4-b27c-600bb36c321f');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/disderot-michel_mortier_disderot_floor_lamp', 'Michel Mortier Disderot Floor Lamp - 10527', 'The Floor Lamp 10527 designed in 1972 by Michel Mortier was published at the time by Verre Lumière. Disderot is reissuing this very current model, with its aluminum base and opaline glass lampshade. Exclusively for Monde Singulier, Disderot is releasing a new version of this iconic lighting in three gradient colors: Beige, Green and Blue. The collection also include the Table Lamp 10497 in the same gradient colors.', 'b6e7b1d1-d9bd-4130-8781-a07cea7c3aa7', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/vova_naumov-the_lamb_collection_armchair', 'The Lamb Chair', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', 'daf021be-405b-4c5a-9832-3098a86fb871', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/vova_naumov-the_lamb_collection_chair_-_little', 'The Little Lamb Chair', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', 'df0797e6-2bf9-48be-a543-2577deb49c0f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-courbes_alléchantes_ceiling_lamp', 'Courbes Alléchantes Ceiling Lamp', 'Axel Chay wants to offer a new vision of his work using fabric on everything. It will change the way you understand the object. The thickness of it will modify shapes and sensation.', '87e41914-41c1-4583-81f0-ac88de7864e7', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-courbes_alléchantes_chair', 'Courbes Alléchantes Chair', 'Axel Chay wants to offer a new vision of his work using fabric on everything. It will change the way you understand the object. The thickness of it will modify shapes and sensation.', '21d28256-06e0-4b6c-b55d-0b4c16317ae1', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/axel_chay-courbes_alléchantes_bench', 'Courbes Alléchantes Bench', 'Axel Chay wants to offer a new vision of his work using fabric on everything. It will change the way you understand the object. The thickness of it will modify shapes and sensation.', '90080742-f69f-403c-b02f-b40487b45846', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/the_lamb_collection', 'The Lamb', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', NULL, NULL, '0c2ede98-b2ed-4b4c-900c-11656220fd47');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/vova_naumov-the_lamb_collection_chair_-_do_re_mi', 'Do Re Mi Chair', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', '8ce94855-aa86-49b3-8a2e-3fd9a0627c54', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_table_lamp', 'Soniah Lightings Table Lamp', 'CABLE LENGTH: 2,5 m, black
Glass lamp plafond x 1
on/off cord foot switch
EU Standard Plug
US, UK plug upon request
Light Source: E27 bulb max 6W (LED only!)
One LED bulb included (only for EU market), 
non dimmable', 'fbdb02ad-d822-411d-a3ba-e00de6ab79e1', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_pendant_lamp_-_m', 'Soniah Lightings Pendant Lamp - M', 'Cable length – 3m
Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable', 'b8bf8c71-3b40-4c4a-b295-47126d741f57', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_pendant_lamp_-_l', 'Soniah Lightings Pendant Lamp - L', 'Cable length – 3m
Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable', '283ad931-79df-4300-ae97-032f504c8ad0', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_wall_sconce_-_s', 'Soniah Lightings Wall Sconce - S', 'Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable', '6a7b2ed1-44bb-48eb-9725-4bf336874326', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_wall_sconce_-_m', 'Soniah Lightings Floor Lamp - M', 'Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable.', 'b469be23-9822-4136-8460-5f8c05b9e87c', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/victoria_yakusha-soniah_lightings_wall_sconce_-_l', 'Soniah Lightings Wall Sconce - L', 'Glass lamp plafond x 1,
1 x E27 bulb,
LED bulb max 60 W
Non-dimmable', 'e9f84a1c-53c7-4b9a-9db5-6b1724593d40', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/victoria_yakusha', 'Soniah Lightings', 'SONIAH collection / for centuries our ancestors lived by the sun, building their lives around solar cycles.  In soniah collection faina walks in their footsteps inspired by the divine power of the sun  “There''s something primal and naturai in following the sun. By following the sun we follow the essence, our true selves, shares Victoria Yakusha.  The SONIAH collection is a manifest of "new primitivism'' in design.  Pure minimalist shapes, crafted with the use of ancient techniques, eliminate the excess, return to the source and revealthe pristine.', NULL, NULL, '7dc08e95-2d17-4934-95b2-d01ced0afd79');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/courbes_alléchantes2', 'Courbes Alléchantes', 'Courbes Alléchantes is an exclusive collection of 5 pieces by the rising star designer Axel Chay.', NULL, NULL, 'afbd3f23-0f68-4a1f-8a4f-4e6c64392c68');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/undum', 'Undum and Bevel', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.   A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.  A relationship with its setting, as well as in the experience they intend to provide for their user.', NULL, NULL, 'fe07ec45-089c-457b-812f-abe2158a248b');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-undum_coffee_table_-_green', 'Undum Coffee Table - Green', 'A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', 'df1e8b02-7787-452e-9afb-35406fbbb6c7', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-undum_coffee_table_-_black', 'Undum Coffee Table - Black', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', '612f5520-0766-4d64-a3ad-e9e662f616cd', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-undum_coffee_table_-_travertin', 'Undum Coffee Table - Travertin', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', 'b5aa4c4b-0dcc-4c33-b5aa-0c4ab923685f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-bevel_bench_-_chrome_mirror', 'Bevel Bench - Chrome Mirror', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', 'e72d6903-73ff-489b-8594-cccee4417005', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-bevel_bench_-_chrome_mirror_black', 'Bevel Bench - Chrome Mirror Black', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', 'f2572947-fc2d-4502-8961-d97d8227c4e3', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-bevel_side_table_-_chrome_mirror', 'Bevel Side Table - Chrome Mirror', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', 'bb996550-b6fb-4753-afe1-a786cce4cc38', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-bevel_side_table_-_chrome_mirror_black', 'Bevel Side Table - Chrome Mirror Black', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', '8a35c385-e311-4176-8e6e-d0f0914f062b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-undum_and_bevel_chair_-_natural', 'Undum and Bevel Chair - Natural', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', '06c25ca2-2913-4957-bc7e-1f569c5001a9', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/hadge-undum_and_bevel_chair_-_black', 'Undum and Bevel Chair - Black', 'A contemporary collection where abstract shapes are reinterpreted and natural materials can thrive.
A cohesion of two simplified curved shapes reflects the softness time of passing by - immaterial element - and plays with the strength of light and setting on the other side - natural element.
A relationship with its setting, as well as in the experience they intend to provide for their user.', '8065cd3b-85d7-47da-ac8a-9fb7572a6c3f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/kann_design-kann---banquette-mi', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', 'e09d049e-0546-41d3-bed9-d235ff0b765c', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/kann_design-kann---mid-sofa', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', '6fffeabd-e876-47b4-ae2d-054a2c37f478', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/thomas_moisan-rodez_armchair', 'Rodez Armchair', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.
The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', 'a68bfa87-ae07-4406-9bd5-dcdefd68599b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/thomas_moisan-rodez_ottoman', 'Rodez Ottoman', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.
The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', '3d2366ae-573c-429d-b95b-c5da1b74c5ea', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/thomas_moisan-rodez_mirror', 'Rodez Mirror', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.
The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', 'acd49219-49ef-4ca1-b0b9-cb050620083e', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/thomas_moisan-rodez_console', 'Rodez Console', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.
The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', 'b98af33c-a100-4657-8941-b82fa6b58cb0', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/thomas_moisan-rodez_coffee_table', 'Rodez Coffee Table', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.
The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', '39c819fb-4712-4288-8444-0d7f1e72fe74', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/thomas_moisan-rodez_side_table', 'Rodez Side Table', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.
The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', '163a823e-cec8-4ad7-9407-b1c5dd42cb1e', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/rodez', 'Rodez', 'This monochrome collection, with its radical lines, takes a modern look at the chromatic universe of lacquered black on a classic base.  The nuances and light effects are set against the background, leaving us to focus on the essentials, creating furniture that stands on its own, stirring emotions.', NULL, NULL, '9a3002a9-3890-49eb-adc2-3c285f35fa51');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/prickly_pear', 'Prickly Pear', 'Anchored and inspired by the Mediterranean region, Mickaël draws from its arid and wild nature that gives birth to his creations.   Intrigued by the prickly pear cactus, which reveals itself to be a natural tool combating soil erosion and contributing to the preservation of the land, Mickaël takes inspiration from it to design this lamp.   Sensuality and softness are the keywords to celebrate this plant. Modeled from the earth protected by the prickly pear, the Pricly Pear wall lamp is born in terracotta through the designer''s hands.   The opaline shades, resembling fleshy berries, radiate and highlight this natural feat.', NULL, NULL, '116ac84a-f08b-4d67-9e2e-331bb1fb0e89');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/sizar_alexis-kursi-chair---natural', 'Kursi Chair - Natural', 'With KURSI I have searched for a more enduring appeal of simplicity and purity in the design process. Its clean lines and sculptural elements are not confined by the limitations of current fads. Instead, they represent a commitment to design that transcends the moment, serving as a reminder of the lasting values of timelessness. The chair''s clean lines and sculptural elements draw inspiration from the captivating aesthetics of architectural geometrical play.', 'ec780ec9-b4fb-4510-b9eb-70a0b04983d8', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/bateaumagne-b-rug-with-pattern-from-helene-paris', 'International - Rug (Pattern by Hélène Paris)', 'BATEAUMAGNE has redesigned the timeless models of its permanent collection in exclusive elegant materials evoking the 70s: stainless steel, smoked glass, speckled woolen cloth and silk. The pure lines of these objects will blend into any interior, bringing that touch of “barefoot luxury” dear to the designer duo.
They worked with artist Hélène Paris for the pattern of their rug. ', '91dafd75-15fd-460b-9eeb-d05b8c5b5248', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/sizar_alexis-kursi-chair---painted', 'Kursi Chair - Painted', 'With KURSI I have searched for a more enduring appeal of simplicity and purity in the design process. Its clean lines and sculptural elements are not confined by the limitations of current fads. Instead, they represent a commitment to design that transcends the moment, serving as a reminder of the lasting values of timelessness. The chair''s clean lines and sculptural elements draw inspiration from the captivating aesthetics of architectural geometrical play.', 'b6adb019-a3d2-485d-9304-9a19105a5b37', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/bateaumagne-bubble-fireside-chair', 'International - Fireside Chair', 'BATEAUMAGNE has redesigned the timeless models of its permanent collection in exclusive elegant materials evoking the 70s: stainless steel, smoked glass, speckled woolen cloth and silk. The pure lines of these objects will blend into any interior, bringing that touch of “barefoot luxury” dear to the designer duo.
They worked with artist Hélène Paris for the pattern of their rug. ', 'ae2c52fe-68e0-4392-91d8-2b7bed0a1330', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/bateaumagne-bubble-bench', 'International - Bench', 'BATEAUMAGNE has redesigned the timeless models of its permanent collection in exclusive elegant materials evoking the 70s: stainless steel, smoked glass, speckled woolen cloth and silk. The pure lines of these objects will blend into any interior, bringing that touch of “barefoot luxury” dear to the designer duo.
They worked with artist Hélène Paris for the pattern of their rug. ', '553bbcbe-e511-47f5-b02d-04a1a6035155', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-round-dining-table', 'Round Dining Table, Stamp by Christophe Perichon, Monde Singulier', 'Round Dining Table, Stamp by Christophe Perichon, Monde Singulier', '57a92d15-3d8f-45bc-95ef-c58035b88bbe', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-side-table', 'Side Table, Stamp by Christophe Perichon, Monde Singulier', 'Side Table, Stamp by Christophe Perichon, Monde Singulier', '6fcc2306-ab13-4066-b592-69ecb9f22717', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-sofa', 'Sofa, Stamp by Christophe Perichon, Monde Singulier', 'Sofa, Stamp by Christophe Perichon, Monde Singulier', 'c36d4300-e054-4fe4-9fe1-c31d8e8a8134', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-table-lamp', 'Table Lamp by Christophe Perichon for Monde Singulier', 'Table Lamp by Christophe Perichon for Monde Singulier', '43ca64e7-acd0-4bfb-ad28-38b0a4116150', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-wall-lamp', 'Wall Lamp by Christophe Perichon for Monde Singulier', 'Wall Lamp by Christophe Perichon for Monde Singulier', 'c1ca4cfb-964e-4c01-8672-0f83429bb3aa', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-oval-dining-table', 'Ovale Dining Table, Stamp by Christophe Perichon, Monde Singulier', 'Ovale Dining Table, Stamp by Christophe Perichon, Monde Singulier', '68764bd5-a128-44d1-9d9f-dfe53e9a4b7c', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/empreintes', 'Stamp by Christophe Perichon for Monde Singulier', 'Stamp by Christophe Perichon for Monde Singulier', NULL, NULL, '45edd364-cb92-41cd-a9d6-3d77c22dc2f8');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/soft_solid', 'Soft Solid', 'SOFT SOLID pays homage to subdued yet confident minimalism, infused with a touch of retro aesthetic. The collection showcases a strong formal approach, utilizing small architectural elements that are able to establish self-contained environments within a room. These austere shapes, rooted in primitive design elements, find a balance through the use of materials like glossy blonde rootwood, complemented by chrome accents, marbles, and pewter elements. The juxtaposition of clean, uncomplicated forms with the inclusion of soft, refined materials imbues the collection with a distinct yet timeless Italian identity.', NULL, NULL, '7c1e9dae-d0fb-412d-a92d-1febb74806ef');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/bateaumagne-b-coffee-table', 'International - Coffee Table', 'BATEAUMAGNE has redesigned the timeless models of its permanent collection in exclusive elegant materials evoking the 70s: stainless steel, smoked glass, speckled woolen cloth and silk. The pure lines of these objects will blend into any interior, bringing that touch of “barefoot luxury” dear to the designer duo.
They worked with artist Hélène Paris for the pattern of their rug. ', 'c2ed02a2-db59-4b0f-a309-53ba9919439a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/jeremy_maxwell_wintrebert_-pinky---table-lamp-l', 'Pinky - Table Lamp L', 'Pinky is a table lamp from the Gamma collection created by Jeremy Maxwell Wintrebert. Exclusively for Monde Singulier, the artist has developed two new limited-edition models, each comprising eight numbered and signed copies.
The glass is freehand, mouth-blown in a marshmallow pink hue and takes a cylindrical shape that captures the light source. The sandblasted finish adds a certain texture to the glass, giving it a soft and sugary appearance. This evocation of soft confectionery is accentuated by an immaculate white aluminum foot, reviving a certain duality with the vanilla-strawberry scent for a nostalgic return to the carefree flavors of childhood.
Due to handcrafted nature, dimension may vary by a few centimeters and there may be slight variation in the color.', 'a8d7cc7d-828d-4876-83c7-3f8892f121f0', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/test', 'Stellar', 'Collection of three asteroids wall lights in walnut and crackled enamel, hand-made in Paris. ', NULL, NULL, '47cf1920-5f83-4b0e-8c6c-13c1354ac550');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/jeremy_maxwell_wintrebert_-pinky---table-lamp-s', 'Pinky - Table Lamp S', 'Pinky is a table lamp from the Gamma collection created by Jeremy Maxwell Wintrebert. Exclusively for Monde Singulier, the artist has developed two new limited-edition models, each comprising eight numbered and signed copies.
The glass is freehand, mouth-blown in a marshmallow pink hue and takes a cylindrical shape that captures the light source. The sandblasted finish adds a certain texture to the glass, giving it a soft and sugary appearance. This evocation of soft confectionery is accentuated by an immaculate white aluminum foot, reviving a certain duality with the vanilla-strawberry scent for a nostalgic return to the carefree flavors of childhood.
Due to handcrafted nature, dimension may vary by a few centimeters and there may be slight variation in the color.', 'e601eccf-471b-4e55-8fd9-229b15be9f56', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/sizar_alexis', 'Kursi Chair', 'With KURSI the designer searched for a more enduring appeal of simplicity and purity in the design process. Its clean lines and sculptural elements are not confined by the limitations of current fads. Instead, they represent a commitment to design that transcends the moment, serving as a reminder of the lasting values of timelessness. The chair''s clean lines and sculptural elements draw inspiration from the captivating aesthetics of architectural geometrical play.', NULL, NULL, 'ec4fb4be-71a3-417d-9dac-6974e61114e3');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/vova_naumov-the_lamb_collection_sofa', 'The Lamb Sofa', 'The lambs is completely inspired by the lamb. The designer used the silhouettes and materials characteristic of the animal so that if you look at the chair, then it literally remind you of a lamb. The soft part embodies the head with twisted horns and the wooden part represent the legs. This chair was the first design of the collection, and it then expand to other subjects where the designer used the same silhouettes.', '512a41e2-b99b-43b9-bd02-025e190cbf98', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/jeremy_maxwell', 'Pinky', 'Pinky is a table lamp from the Gamma collection created by Jeremy Maxwell Wintrebert. Exclusively for Monde Singulier, the artist has developed two new limited-edition models, each comprising eight numbered and signed copies.
The glass is freehand, mouth-blown in a marshmallow pink hue and takes a cylindrical shape that captures the light source. The sandblasted finish adds a certain texture to the glass, giving it a soft and sugary appearance. This evocation of soft confectionery is accentuated by an immaculate white aluminum foot, reviving a certain duality with the vanilla-strawberry scent for a nostalgic return to the carefree flavors of childhood.', NULL, NULL, 'f7a9eb2e-a6c9-436f-98c2-03fe62d46547');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/bateaumagne', 'International', 'BATEAUMAGNE has redesigned the timeless models of its permanent collection in exclusive elegant materials evoking the 70s: stainless steel, smoked glass, speckled woolen cloth and silk. The pure lines of these objects will blend into any interior, bringing that touch of “barefoot luxury” dear to the designer duo.
They worked with artist Hélène Paris for the pattern of their rug. ', NULL, NULL, '19d5ad93-4c4d-40b2-8b62-c0a07d61815b');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/johanna_de_clisson_-_hiromi-stellar-wall-lamp---ida', 'Stellar Wall Lamp - Ida', 'Collection of three asteroids wall lights in walnut and crackled enamel, hand-made in Paris. ', '0c3ead76-422d-4c0e-9aba-925f72f6081b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/johanna_de_clisson_-_hiromi-ceres', 'Cérès', 'Collection of three asteroids wall lights in walnut and crackled enamel, hand-made in Paris. ', 'f7202b8b-cd8a-4178-b407-82db5a6bb498', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/johanna_de_clisson_-_hiromi-stellar-wall-lamp---eros', 'Stellar Wall Lamp - Éros', 'Collection of three asteroids wall lights in walnut and crackled enamel, hand-made in Paris. ', '3ee12474-17ab-4c84-b481-facde72e56c3', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-armchair', 'Armchair by Christophe Perichon for Monde Singulier', 'Armchair by Christophe Perichon for Monde Singulier', '03a0ff56-736e-445b-af62-6109118bdf88', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-barstool', 'Christophe Perichon for Monde Singulier', 'Christophe Perichon for Monde Singulier', '35c1bee5-f918-4998-8aec-4b8e27506a5f', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-bookcase', 'Christophe Perichon for Monde Singulier', 'Christophe Perichon for Monde Singulier', '3c7493c6-172a-491c-a729-68d61ddd0e5e', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-chair', 'Christophe Perichon for Monde Singulier', 'Christophe Perichon for Monde Singulier', '1e75e1ab-e555-4cbb-a2b2-bf9f7f4761c4', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-coffee-table', 'Christophe Perichon for Monde Singulier', 'Christophe Perichon for Monde Singulier', '57cf8def-b32f-43e6-9071-89e1d630824b', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-console', 'Christophe Perichon for Monde Singulier', 'Christophe Perichon for Monde Singulier', '0fd61ffd-6fae-4797-99e1-6b8fc788e00a', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-desk', 'Christophe Perichon for Monde Singulier', 'Christophe Perichon for Monde Singulier', 'd0a162e6-bc9a-4f4d-9627-7585ac26fcbb', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/christophe_perichon-floor-lamp', 'Floor Lamp, Stamp by Christophe Perichon, Monde Singulier', 'Floor Lamp, Stamp by Christophe Perichon, Monde Singulier', '0ba3ca36-3c35-4e5b-931f-206af55931b7', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/kann_design', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', NULL, NULL, 'caa16d22-fb0c-4ab4-9ade-9a96a758ef1b');
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/kann_design-kann---galta-forte-dining-table', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', 'd9cc0889-b7e1-4a41-9462-5d10121edf74', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/kann_design-kann---galta-forte-rectangle-coffee-table', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', '2ff4df0e-d1f4-460f-b13e-eb8308c4db05', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/kann_design-kann---galta-forte-round-coffee-table', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', '8bfbdb57-fbc6-449c-9f29-ecb0fa5a5191', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/kann_design-kann---galta-forte-side-table', 'Kann Design for Monde Singulier', 'Kann Design for Monde Singulier', '4652802e-5fbf-4c1e-bf10-08c7734d3979', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/product/rispal_x_lucas_castex-mante-religieuse---floor-lamp', 'Rispal, Lucas Castex, Mante Religieuse Monde Singulier', 'Rispal, Lucas Castex, Mante Religieuse Monde Singulier', '0b93c60c-4079-4524-9364-aa67bc2ffbd3', NULL, NULL);
INSERT INTO public.seo (id, title, description, "MSProductId", "ArtistBrandId", "MSCollectionId") VALUES ('ms://seo/collection/la_mante_religieuse', 'Mante Religieuse by Rispal and Lucas Castex exclusively for Monde Singulier', 'Mante Religieuse by Rispal and Lucas Castex exclusively for Monde Singulier', NULL, NULL, '11c68998-9b27-4106-af44-8b75be7e19f5');

ALTER TABLE public.seo ENABLE TRIGGER ALL;